//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.24 at 11:07:35 AM CEST 
//


package com.deev.interaction.uav3i.util.paparazzi_settings.airframe.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{}include"/>
 *         &lt;element ref="{}servos"/>
 *         &lt;element ref="{}commands"/>
 *         &lt;element ref="{}rc_commands"/>
 *         &lt;element ref="{}auto_rc_commands"/>
 *         &lt;element ref="{}ap_only_commands"/>
 *         &lt;element ref="{}command_laws"/>
 *         &lt;element ref="{}section"/>
 *         &lt;element ref="{}makefile"/>
 *         &lt;element ref="{}modules"/>
 *         &lt;element ref="{}firmware"/>
 *         &lt;element ref="{}autopilot"/>
 *       &lt;/choice>
 *       &lt;attGroup ref="{}attlist.airframe"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "includeOrServosOrCommands"
})
@XmlRootElement(name = "airframe")
public class Airframe {

    @XmlElements({
        @XmlElement(name = "include", type = Include.class),
        @XmlElement(name = "servos", type = Servos.class),
        @XmlElement(name = "commands", type = Commands.class),
        @XmlElement(name = "rc_commands", type = RcCommands.class),
        @XmlElement(name = "auto_rc_commands", type = AutoRcCommands.class),
        @XmlElement(name = "ap_only_commands", type = ApOnlyCommands.class),
        @XmlElement(name = "command_laws", type = CommandLaws.class),
        @XmlElement(name = "section", type = Section.class),
        @XmlElement(name = "makefile", type = Makefile.class),
        @XmlElement(name = "modules", type = Modules.class),
        @XmlElement(name = "firmware", type = Firmware.class),
        @XmlElement(name = "autopilot", type = Autopilot.class)
    })
    protected List<Object> includeOrServosOrCommands;
    @XmlAttribute(name = "name")
    @XmlSchemaType(name = "anySimpleType")
    protected String name;

    /**
     * Gets the value of the includeOrServosOrCommands property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the includeOrServosOrCommands property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIncludeOrServosOrCommands().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Include }
     * {@link Servos }
     * {@link Commands }
     * {@link RcCommands }
     * {@link AutoRcCommands }
     * {@link ApOnlyCommands }
     * {@link CommandLaws }
     * {@link Section }
     * {@link Makefile }
     * {@link Modules }
     * {@link Firmware }
     * {@link Autopilot }
     * 
     * 
     */
    public List<Object> getIncludeOrServosOrCommands() {
        if (includeOrServosOrCommands == null) {
            includeOrServosOrCommands = new ArrayList<Object>();
        }
        return this.includeOrServosOrCommands;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
