//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.24 at 11:07:35 AM CEST 
//


package com.deev.interaction.uav3i.util.paparazzi_settings.airframe.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.deev.interaction.uav3i.util.paparazzi_settings.airframe.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.deev.interaction.uav3i.util.paparazzi_settings.airframe.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Call }
     * 
     */
    public Call createCall() {
        return new Call();
    }

    /**
     * Create an instance of {@link Set }
     * 
     */
    public Set createSet() {
        return new Set();
    }

    /**
     * Create an instance of {@link Commands }
     * 
     */
    public Commands createCommands() {
        return new Commands();
    }

    /**
     * Create an instance of {@link Axis }
     * 
     */
    public Axis createAxis() {
        return new Axis();
    }

    /**
     * Create an instance of {@link Autopilot }
     * 
     */
    public Autopilot createAutopilot() {
        return new Autopilot();
    }

    /**
     * Create an instance of {@link Servos }
     * 
     */
    public Servos createServos() {
        return new Servos();
    }

    /**
     * Create an instance of {@link Servo }
     * 
     */
    public Servo createServo() {
        return new Servo();
    }

    /**
     * Create an instance of {@link Configure }
     * 
     */
    public Configure createConfigure() {
        return new Configure();
    }

    /**
     * Create an instance of {@link Copy }
     * 
     */
    public Copy createCopy() {
        return new Copy();
    }

    /**
     * Create an instance of {@link Define }
     * 
     */
    public Define createDefine() {
        return new Define();
    }

    /**
     * Create an instance of {@link Firmware }
     * 
     */
    public Firmware createFirmware() {
        return new Firmware();
    }

    /**
     * Create an instance of {@link Target }
     * 
     */
    public Target createTarget() {
        return new Target();
    }

    /**
     * Create an instance of {@link Subsystem }
     * 
     */
    public Subsystem createSubsystem() {
        return new Subsystem();
    }

    /**
     * Create an instance of {@link Linear }
     * 
     */
    public Linear createLinear() {
        return new Linear();
    }

    /**
     * Create an instance of {@link AutoRcCommands }
     * 
     */
    public AutoRcCommands createAutoRcCommands() {
        return new AutoRcCommands();
    }

    /**
     * Create an instance of {@link Let }
     * 
     */
    public Let createLet() {
        return new Let();
    }

    /**
     * Create an instance of {@link CommandLaws }
     * 
     */
    public CommandLaws createCommandLaws() {
        return new CommandLaws();
    }

    /**
     * Create an instance of {@link Ratelimit }
     * 
     */
    public Ratelimit createRatelimit() {
        return new Ratelimit();
    }

    /**
     * Create an instance of {@link Airframe }
     * 
     */
    public Airframe createAirframe() {
        return new Airframe();
    }

    /**
     * Create an instance of {@link Include }
     * 
     */
    public Include createInclude() {
        return new Include();
    }

    /**
     * Create an instance of {@link RcCommands }
     * 
     */
    public RcCommands createRcCommands() {
        return new RcCommands();
    }

    /**
     * Create an instance of {@link ApOnlyCommands }
     * 
     */
    public ApOnlyCommands createApOnlyCommands() {
        return new ApOnlyCommands();
    }

    /**
     * Create an instance of {@link Section }
     * 
     */
    public Section createSection() {
        return new Section();
    }

    /**
     * Create an instance of {@link Makefile }
     * 
     */
    public Makefile createMakefile() {
        return new Makefile();
    }

    /**
     * Create an instance of {@link Modules }
     * 
     */
    public Modules createModules() {
        return new Modules();
    }

    /**
     * Create an instance of {@link Load }
     * 
     */
    public Load createLoad() {
        return new Load();
    }

}
