//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.18 at 04:07:31 PM CEST 
//


package eu.telecom_bretagne.uav3i.flight_plan.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}header" minOccurs="0"/>
 *         &lt;element ref="{}waypoints"/>
 *         &lt;element ref="{}sectors" minOccurs="0"/>
 *         &lt;element ref="{}includes" minOccurs="0"/>
 *         &lt;element ref="{}exceptions" minOccurs="0"/>
 *         &lt;element ref="{}blocks"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{}attlist.flight_plan"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "header",
    "waypoints",
    "sectors",
    "includes",
    "exceptions",
    "blocks"
})
@XmlRootElement(name = "flight_plan")
public class FlightPlan {

    protected String header;
    @XmlElement(required = true)
    protected Waypoints waypoints;
    protected Sectors sectors;
    protected Includes includes;
    protected Exceptions exceptions;
    @XmlElement(required = true)
    protected Blocks blocks;
    @XmlAttribute(name = "name", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String name;
    @XmlAttribute(name = "lat0", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String lat0;
    @XmlAttribute(name = "lon0", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String lon0;
    @XmlAttribute(name = "max_dist_from_home", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String maxDistFromHome;
    @XmlAttribute(name = "ground_alt", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String groundAlt;
    @XmlAttribute(name = "security_height", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String securityHeight;
    @XmlAttribute(name = "alt", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String alt;
    @XmlAttribute(name = "qfu")
    @XmlSchemaType(name = "anySimpleType")
    protected String qfu;
    @XmlAttribute(name = "home_mode_height")
    @XmlSchemaType(name = "anySimpleType")
    protected String homeModeHeight;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeader(String value) {
        this.header = value;
    }

    /**
     * Gets the value of the waypoints property.
     * 
     * @return
     *     possible object is
     *     {@link Waypoints }
     *     
     */
    public Waypoints getWaypoints() {
        return waypoints;
    }

    /**
     * Sets the value of the waypoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link Waypoints }
     *     
     */
    public void setWaypoints(Waypoints value) {
        this.waypoints = value;
    }

    /**
     * Gets the value of the sectors property.
     * 
     * @return
     *     possible object is
     *     {@link Sectors }
     *     
     */
    public Sectors getSectors() {
        return sectors;
    }

    /**
     * Sets the value of the sectors property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sectors }
     *     
     */
    public void setSectors(Sectors value) {
        this.sectors = value;
    }

    /**
     * Gets the value of the includes property.
     * 
     * @return
     *     possible object is
     *     {@link Includes }
     *     
     */
    public Includes getIncludes() {
        return includes;
    }

    /**
     * Sets the value of the includes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Includes }
     *     
     */
    public void setIncludes(Includes value) {
        this.includes = value;
    }

    /**
     * Gets the value of the exceptions property.
     * 
     * @return
     *     possible object is
     *     {@link Exceptions }
     *     
     */
    public Exceptions getExceptions() {
        return exceptions;
    }

    /**
     * Sets the value of the exceptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Exceptions }
     *     
     */
    public void setExceptions(Exceptions value) {
        this.exceptions = value;
    }

    /**
     * Gets the value of the blocks property.
     * 
     * @return
     *     possible object is
     *     {@link Blocks }
     *     
     */
    public Blocks getBlocks() {
        return blocks;
    }

    /**
     * Sets the value of the blocks property.
     * 
     * @param value
     *     allowed object is
     *     {@link Blocks }
     *     
     */
    public void setBlocks(Blocks value) {
        this.blocks = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the lat0 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLat0() {
        return lat0;
    }

    /**
     * Sets the value of the lat0 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLat0(String value) {
        this.lat0 = value;
    }

    /**
     * Gets the value of the lon0 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLon0() {
        return lon0;
    }

    /**
     * Sets the value of the lon0 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLon0(String value) {
        this.lon0 = value;
    }

    /**
     * Gets the value of the maxDistFromHome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxDistFromHome() {
        return maxDistFromHome;
    }

    /**
     * Sets the value of the maxDistFromHome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxDistFromHome(String value) {
        this.maxDistFromHome = value;
    }

    /**
     * Gets the value of the groundAlt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroundAlt() {
        return groundAlt;
    }

    /**
     * Sets the value of the groundAlt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroundAlt(String value) {
        this.groundAlt = value;
    }

    /**
     * Gets the value of the securityHeight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecurityHeight() {
        return securityHeight;
    }

    /**
     * Sets the value of the securityHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecurityHeight(String value) {
        this.securityHeight = value;
    }

    /**
     * Gets the value of the alt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlt() {
        return alt;
    }

    /**
     * Sets the value of the alt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlt(String value) {
        this.alt = value;
    }

    /**
     * Gets the value of the qfu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQfu() {
        return qfu;
    }

    /**
     * Sets the value of the qfu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQfu(String value) {
        this.qfu = value;
    }

    /**
     * Gets the value of the homeModeHeight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHomeModeHeight() {
        return homeModeHeight;
    }

    /**
     * Sets the value of the homeModeHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHomeModeHeight(String value) {
        this.homeModeHeight = value;
    }

}
