//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.18 at 12:25:32 PM CEST 
//


package eu.telecom_bretagne.uav3i.flight_plan.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attGroup ref="{}attlist.survey_rectangle"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "survey_rectangle")
public class SurveyRectangle {

    @XmlAttribute(name = "grid", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String grid;
    @XmlAttribute(name = "orientation")
    @XmlSchemaType(name = "anySimpleType")
    protected String orientation;
    @XmlAttribute(name = "wp1", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String wp1;
    @XmlAttribute(name = "wp2", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String wp2;

    /**
     * Gets the value of the grid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGrid() {
        return grid;
    }

    /**
     * Sets the value of the grid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGrid(String value) {
        this.grid = value;
    }

    /**
     * Gets the value of the orientation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrientation() {
        return orientation;
    }

    /**
     * Sets the value of the orientation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrientation(String value) {
        this.orientation = value;
    }

    /**
     * Gets the value of the wp1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWp1() {
        return wp1;
    }

    /**
     * Sets the value of the wp1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWp1(String value) {
        this.wp1 = value;
    }

    /**
     * Gets the value of the wp2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWp2() {
        return wp2;
    }

    /**
     * Sets the value of the wp2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWp2(String value) {
        this.wp2 = value;
    }

}
