//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.19 at 10:11:57 AM CEST 
//


package eu.telecom_bretagne.uav3i.paparazzi_settings.airframe.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{}let"/>
 *         &lt;element ref="{}set"/>
 *         &lt;element ref="{}ratelimit"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "letOrSetOrRatelimit"
})
@XmlRootElement(name = "command_laws")
public class CommandLaws {

    @XmlElements({
        @XmlElement(name = "let", type = Let.class),
        @XmlElement(name = "set", type = Set.class),
        @XmlElement(name = "ratelimit", type = Ratelimit.class)
    })
    protected List<Object> letOrSetOrRatelimit;

    /**
     * Gets the value of the letOrSetOrRatelimit property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the letOrSetOrRatelimit property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLetOrSetOrRatelimit().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Let }
     * {@link Set }
     * {@link Ratelimit }
     * 
     * 
     */
    public List<Object> getLetOrSetOrRatelimit() {
        if (letOrSetOrRatelimit == null) {
            letOrSetOrRatelimit = new ArrayList<Object>();
        }
        return this.letOrSetOrRatelimit;
    }

}
