//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.19 at 10:11:57 AM CEST 
//


package eu.telecom_bretagne.uav3i.paparazzi_settings.airframe.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attGroup ref="{}attlist.field_map"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "field_map")
public class FieldMap {

    @XmlAttribute(name = "field", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String field;
    @XmlAttribute(name = "servo_id", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String servoId;

    /**
     * Gets the value of the field property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getField() {
        return field;
    }

    /**
     * Sets the value of the field property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setField(String value) {
        this.field = value;
    }

    /**
     * Gets the value of the servoId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServoId() {
        return servoId;
    }

    /**
     * Sets the value of the servoId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServoId(String value) {
        this.servoId = value;
    }

}
